# Generated by Django 5.0.7 on 2024-08-10 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_goal_target_purpose_profile_gender_workout_distance_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='goal',
            old_name='target_purpose',
            new_name='purpose_to_train',
        ),
    ]
